import { test, expect } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { register } from '../tool/fixture-accounts.js';
import { base } from '../tool/local-server.js';

const key = 'mutual-chat:session:v1';
test('encrypted local session resumes the same device, protects lock ownership and decrypts old history', async ({ page, context }, info) => {
  const suffix = randomBytes(5).toString('hex'); const password = randomBytes(24).toString('hex');
  const passphrase = 'local-fixture-' + randomBytes(24).toString('hex');
  const user = await register('restore_' + suffix, password); let logins = 0;
  page.on('request', r => { if (r.url().endsWith('/login') && r.method() === 'POST') logins++; });
  await page.goto('/'); await page.getByLabel('服务器地址').fill(base); await page.getByLabel('用户 ID').fill(user);
  await page.getByLabel('密码', { exact: true }).fill(password); await page.getByLabel('在此浏览器保留会话').check();
  await page.locator('#local-passphrase').fill(passphrase);
  const response = page.waitForResponse(r => r.url().endsWith('/_matrix/client/v3/login') && r.request().method() === 'POST');
  await page.getByRole('button', { name: '连接', exact: true }).click(); const auth = await (await response).json();
  await expect(page.locator('#chat')).toBeVisible(); await expect(page.locator('#device')).toContainText(auth.device_id);
  const sealed = await page.evaluate(key => localStorage.getItem(key), key); expect(sealed).toBeTruthy();
  for (const secret of [auth.access_token, auth.device_id, user, password, passphrase]) expect(sealed).not.toContain(secret);
  const room = '恢复验收 ' + suffix;
  page.on('dialog', d => d.accept());
  await expect(page.getByRole('button', { name: '新建会话' })).toBeEnabled(); await page.getByRole('button', { name: '新建会话' }).click();
  await page.getByLabel('会话名称', { exact: true }).fill(room); await page.getByRole('button', { name: '创建加密会话', exact: true }).click();
  const original = '刷新前加密消息 ' + suffix;
  await expect(page.getByRole('button', { name: '发送', exact: true })).toBeEnabled();
  await page.getByRole('textbox', { name: '消息', exact: true }).fill(original);
  const sent = page.waitForResponse(r => r.url().includes('/send/m.room.encrypted/') && r.status() === 200);
  await page.getByRole('button', { name: '发送', exact: true }).click(); await sent;
  await page.reload(); await expect(page.locator('#unlock')).toBeVisible();
  await page.locator('#unlock-passphrase').fill('incorrect-long-local-passphrase');
  await page.getByRole('button', { name: '解锁', exact: true }).click();
  await expect(page.locator('#status')).toContainText('无法解锁');
  expect(await page.evaluate(key => localStorage.getItem(key), key)).toBe(sealed);
  await page.locator('#unlock-passphrase').fill(passphrase); await page.getByRole('button', { name: '解锁', exact: true }).click();
  await expect(page.locator('#chat')).toBeVisible(); await expect(page.locator('#device')).toContainText(auth.device_id);
  await page.getByRole('button', { name: room, exact: true }).click(); await expect(page.getByRole('log')).toContainText(original);
  expect(logins).toBe(1);
  const second = await context.newPage(); await second.goto('/');
  await second.locator('#unlock-passphrase').fill(passphrase); await second.getByRole('button', { name: '解锁', exact: true }).click();
  await expect(second.locator('#status')).toContainText('已有聊天窗口');
  await expect(second.locator('#chat')).toBeHidden(); await expect(page.locator('#chat')).toBeVisible();
  await page.getByRole('button', { name: '锁定', exact: true }).click(); await expect(page.locator('#unlock')).toBeVisible();
  await second.locator('#unlock-passphrase').fill(passphrase); await second.getByRole('button', { name: '解锁', exact: true }).click();
  await expect(second.locator('#chat')).toBeVisible(); await expect(second.locator('#device')).toContainText(auth.device_id);
  await second.getByRole('button', { name: room, exact: true }).click(); await expect(second.getByRole('log')).toContainText(original);
  const continued = '解锁后继续发送 ' + suffix;
  await second.getByRole('textbox', { name: '消息', exact: true }).fill(continued);
  const sentAgain = second.waitForResponse(r => r.url().includes('/send/m.room.encrypted/') && r.status() === 200);
  await second.getByRole('button', { name: '发送', exact: true }).click(); await sentAgain;
  await expect(second.getByRole('log')).toContainText(continued);
  await second.screenshot({ path: info.outputPath('restored-session.png'), fullPage: true });
  const headers = { Authorization: `Bearer ${auth.access_token}` };
  const who = await (await fetch(base + '/_matrix/client/v3/account/whoami', { headers })).json(); expect(who.device_id).toBe(auth.device_id);
  second.on('dialog', d => d.accept()); await second.getByRole('button', { name: '退出帐号', exact: true }).click();
  await expect(second.locator('#login')).toBeVisible();
  expect(await second.evaluate(key => localStorage.getItem(key), key)).toBeNull();
  expect((await fetch(base + '/_matrix/client/v3/account/whoami', { headers })).status).toBe(401);
  await second.close();
});

test('revoked saved token remains locked and is not silently replaced with a new login', async ({ page }) => {
  const password = randomBytes(24).toString('hex'); const passphrase = 'local-' + randomBytes(24).toString('hex');
  const user = await register('revoked_' + randomBytes(5).toString('hex'), password);
  await page.goto('/'); await page.getByLabel('服务器地址').fill(base); await page.getByLabel('用户 ID').fill(user);
  await page.getByLabel('密码', { exact: true }).fill(password); await page.getByLabel('在此浏览器保留会话').check();
  await page.locator('#local-passphrase').fill(passphrase);
  const login = page.waitForResponse(r => r.url().endsWith('/_matrix/client/v3/login') && r.request().method() === 'POST');
  await page.getByRole('button', { name: '连接', exact: true }).click(); const auth = await (await login).json();
  await expect(page.locator('#chat')).toBeVisible(); await page.getByRole('button', { name: '锁定', exact: true }).click();
  expect((await fetch(base + '/_matrix/client/v3/logout', { method: 'POST', headers: { Authorization: `Bearer ${auth.access_token}` } })).status).toBe(200);
  const sealed = await page.evaluate(key => localStorage.getItem(key), key);
  await page.locator('#unlock-passphrase').fill(passphrase); await page.getByRole('button', { name: '解锁', exact: true }).click();
  await expect(page.locator('#status')).toContainText('保存的登录已失效'); await expect(page.locator('#chat')).toBeHidden();
  expect(await page.evaluate(key => localStorage.getItem(key), key)).toBe(sealed);
});
